### ISSUE TITLE
Comparison to the yansi crate?

### ISSUE THREAD

**Issue by ghost** [botika/yansi-term#3]
Would it be possible to document how this would be compared to [yansi](https://lib.rs/crates/yansi), or the crate it was forked from, please?

I do see the additional dependencies but the usage seems to be similar on the surface, so figured I would ask. Thanks in advance.

**Comment by zzau13** [comment]
You can read at README.md, 

https://github.com/botika/yansi-term/blame/master/README.md#L2-L4

It is made to avoid intermediate allocation and to migrate it to buf-min. As marked in the README and in the issues. 

I don't understand the reason for the issue, when you haven't looked at the README. Could you tell me what a person thinks of to open an issue like this? 
It is a mystery to me.
